# (c) William Belle, 2019-2025.
# See the LICENSE file for more details.

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node.js ${{ matrix.node }} CI

    strategy:
      fail-fast: false
      matrix:
        node: [ '18', '19', '20' ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install and coverage
        run: |
          npm i
          npm run coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: node-${{ matrix.node }}
          parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    name: Coveralls

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "node-18,node-19"
